package com.broduck.enigma.generate.dao;

import com.broduck.enigma.generate.model.VoteItemDetail;
import com.broduck.enigma.generate.model.VoteItemDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteItemDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    long countByExample(VoteItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int deleteByExample(VoteItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer voteItemDetailSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int insert(VoteItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int insertSelective(VoteItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    List<VoteItemDetail> selectByExampleWithRowbounds(VoteItemDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    List<VoteItemDetail> selectByExample(VoteItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    VoteItemDetail selectByPrimaryKey(Integer voteItemDetailSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteItemDetail record, @Param("example") VoteItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteItemDetail record, @Param("example") VoteItemDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteItemDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitemdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteItemDetail record);
}