package com.broduck.enigma.generate.dao;

import com.broduck.enigma.generate.model.VoteResult;
import com.broduck.enigma.generate.model.VoteResultExample;
import com.broduck.enigma.generate.model.VoteResultKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    long countByExample(VoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int deleteByExample(VoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VoteResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int insert(VoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int insertSelective(VoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    List<VoteResult> selectByExampleWithRowbounds(VoteResultExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    List<VoteResult> selectByExample(VoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    VoteResult selectByPrimaryKey(VoteResultKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteResult record, @Param("example") VoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteResult record, @Param("example") VoteResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteResult record);
}