package com.broduck.enigma.generate.dao;

import com.broduck.enigma.generate.model.VoteItem;
import com.broduck.enigma.generate.model.VoteItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    long countByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int deleteByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer voteItemSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int insert(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int insertSelective(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    List<VoteItem> selectByExampleWithRowbounds(VoteItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    List<VoteItem> selectByExample(VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    VoteItem selectByPrimaryKey(Integer voteItemSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteItem record, @Param("example") VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteItem record, @Param("example") VoteItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteItem record);
}