package com.broduck.enigma.generate.dao;

import com.broduck.enigma.generate.model.VoteJoinMember;
import com.broduck.enigma.generate.model.VoteJoinMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VoteJoinMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    long countByExample(VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int deleteByExample(VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer voteJoinSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int insert(VoteJoinMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int insertSelective(VoteJoinMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    List<VoteJoinMember> selectByExampleWithBLOBsWithRowbounds(VoteJoinMemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    List<VoteJoinMember> selectByExampleWithBLOBs(VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    List<VoteJoinMember> selectByExampleWithRowbounds(VoteJoinMemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    List<VoteJoinMember> selectByExample(VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    VoteJoinMember selectByPrimaryKey(Integer voteJoinSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VoteJoinMember record, @Param("example") VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") VoteJoinMember record, @Param("example") VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VoteJoinMember record, @Param("example") VoteJoinMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteJoinMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(VoteJoinMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteJoinMember record);
}