package com.broduck.enigma.generate.model;

import java.io.Serializable;

public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_sn
     *
     * @mbg.generated
     */
    private Integer memberSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.male_yn
     *
     * @mbg.generated
     */
    private Boolean maleYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_sn
     *
     * @return the value of member.member_sn
     *
     * @mbg.generated
     */
    public Integer getMemberSn() {
        return memberSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_sn
     *
     * @param memberSn the value for member.member_sn
     *
     * @mbg.generated
     */
    public void setMemberSn(Integer memberSn) {
        this.memberSn = memberSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.nickname
     *
     * @return the value of member.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.nickname
     *
     * @param nickname the value for member.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.male_yn
     *
     * @return the value of member.male_yn
     *
     * @mbg.generated
     */
    public Boolean getMaleYn() {
        return maleYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.male_yn
     *
     * @param maleYn the value for member.male_yn
     *
     * @mbg.generated
     */
    public void setMaleYn(Boolean maleYn) {
        this.maleYn = maleYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age
     *
     * @return the value of member.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age
     *
     * @param age the value for member.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Member other = (Member) that;
        return (this.getMemberSn() == null ? other.getMemberSn() == null : this.getMemberSn().equals(other.getMemberSn()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getMaleYn() == null ? other.getMaleYn() == null : this.getMaleYn().equals(other.getMaleYn()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMemberSn() == null) ? 0 : getMemberSn().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getMaleYn() == null) ? 0 : getMaleYn().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", memberSn=").append(memberSn);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", maleYn=").append(maleYn);
        sb.append(", age=").append(age);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}