package com.broduck.enigma.generate.model;

import java.util.ArrayList;
import java.util.List;

public class VoteResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public VoteResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoteSnIsNull() {
            addCriterion("vote_sn is null");
            return (Criteria) this;
        }

        public Criteria andVoteSnIsNotNull() {
            addCriterion("vote_sn is not null");
            return (Criteria) this;
        }

        public Criteria andVoteSnEqualTo(Integer value) {
            addCriterion("vote_sn =", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotEqualTo(Integer value) {
            addCriterion("vote_sn <>", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnGreaterThan(Integer value) {
            addCriterion("vote_sn >", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_sn >=", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnLessThan(Integer value) {
            addCriterion("vote_sn <", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnLessThanOrEqualTo(Integer value) {
            addCriterion("vote_sn <=", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnIn(List<Integer> values) {
            addCriterion("vote_sn in", values, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotIn(List<Integer> values) {
            addCriterion("vote_sn not in", values, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnBetween(Integer value1, Integer value2) {
            addCriterion("vote_sn between", value1, value2, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_sn not between", value1, value2, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnIsNull() {
            addCriterion("vote_item_sn is null");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnIsNotNull() {
            addCriterion("vote_item_sn is not null");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnEqualTo(Integer value) {
            addCriterion("vote_item_sn =", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnNotEqualTo(Integer value) {
            addCriterion("vote_item_sn <>", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnGreaterThan(Integer value) {
            addCriterion("vote_item_sn >", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_item_sn >=", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnLessThan(Integer value) {
            addCriterion("vote_item_sn <", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnLessThanOrEqualTo(Integer value) {
            addCriterion("vote_item_sn <=", value, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnIn(List<Integer> values) {
            addCriterion("vote_item_sn in", values, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnNotIn(List<Integer> values) {
            addCriterion("vote_item_sn not in", values, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnBetween(Integer value1, Integer value2) {
            addCriterion("vote_item_sn between", value1, value2, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andVoteItemSnNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_item_sn not between", value1, value2, "voteItemSn");
            return (Criteria) this;
        }

        public Criteria andAgeKindIsNull() {
            addCriterion("age_kind is null");
            return (Criteria) this;
        }

        public Criteria andAgeKindIsNotNull() {
            addCriterion("age_kind is not null");
            return (Criteria) this;
        }

        public Criteria andAgeKindEqualTo(Integer value) {
            addCriterion("age_kind =", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindNotEqualTo(Integer value) {
            addCriterion("age_kind <>", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindGreaterThan(Integer value) {
            addCriterion("age_kind >", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindGreaterThanOrEqualTo(Integer value) {
            addCriterion("age_kind >=", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindLessThan(Integer value) {
            addCriterion("age_kind <", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindLessThanOrEqualTo(Integer value) {
            addCriterion("age_kind <=", value, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindIn(List<Integer> values) {
            addCriterion("age_kind in", values, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindNotIn(List<Integer> values) {
            addCriterion("age_kind not in", values, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindBetween(Integer value1, Integer value2) {
            addCriterion("age_kind between", value1, value2, "ageKind");
            return (Criteria) this;
        }

        public Criteria andAgeKindNotBetween(Integer value1, Integer value2) {
            addCriterion("age_kind not between", value1, value2, "ageKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindIsNull() {
            addCriterion("male_kind is null");
            return (Criteria) this;
        }

        public Criteria andMaleKindIsNotNull() {
            addCriterion("male_kind is not null");
            return (Criteria) this;
        }

        public Criteria andMaleKindEqualTo(Boolean value) {
            addCriterion("male_kind =", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindNotEqualTo(Boolean value) {
            addCriterion("male_kind <>", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindGreaterThan(Boolean value) {
            addCriterion("male_kind >", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindGreaterThanOrEqualTo(Boolean value) {
            addCriterion("male_kind >=", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindLessThan(Boolean value) {
            addCriterion("male_kind <", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindLessThanOrEqualTo(Boolean value) {
            addCriterion("male_kind <=", value, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindIn(List<Boolean> values) {
            addCriterion("male_kind in", values, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindNotIn(List<Boolean> values) {
            addCriterion("male_kind not in", values, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindBetween(Boolean value1, Boolean value2) {
            addCriterion("male_kind between", value1, value2, "maleKind");
            return (Criteria) this;
        }

        public Criteria andMaleKindNotBetween(Boolean value1, Boolean value2) {
            addCriterion("male_kind not between", value1, value2, "maleKind");
            return (Criteria) this;
        }

        public Criteria andVoteCountIsNull() {
            addCriterion("vote_count is null");
            return (Criteria) this;
        }

        public Criteria andVoteCountIsNotNull() {
            addCriterion("vote_count is not null");
            return (Criteria) this;
        }

        public Criteria andVoteCountEqualTo(Integer value) {
            addCriterion("vote_count =", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountNotEqualTo(Integer value) {
            addCriterion("vote_count <>", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountGreaterThan(Integer value) {
            addCriterion("vote_count >", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_count >=", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountLessThan(Integer value) {
            addCriterion("vote_count <", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountLessThanOrEqualTo(Integer value) {
            addCriterion("vote_count <=", value, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountIn(List<Integer> values) {
            addCriterion("vote_count in", values, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountNotIn(List<Integer> values) {
            addCriterion("vote_count not in", values, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountBetween(Integer value1, Integer value2) {
            addCriterion("vote_count between", value1, value2, "voteCount");
            return (Criteria) this;
        }

        public Criteria andVoteCountNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_count not between", value1, value2, "voteCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteresult
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteresult
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}