package com.broduck.enigma.generate.model;

import java.io.Serializable;
import java.util.Date;

public class Vote implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_sn
     *
     * @mbg.generated
     */
    private Integer voteSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.category_sn
     *
     * @mbg.generated
     */
    private Integer categorySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_name
     *
     * @mbg.generated
     */
    private String voteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.finish_yn
     *
     * @mbg.generated
     */
    private Boolean finishYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.target_config_yn
     *
     * @mbg.generated
     */
    private Boolean targetConfigYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.target_vote_count
     *
     * @mbg.generated
     */
    private Integer targetVoteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.age_open_yn
     *
     * @mbg.generated
     */
    private Boolean ageOpenYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.sex_open_yn
     *
     * @mbg.generated
     */
    private Boolean sexOpenYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.private_open_yn
     *
     * @mbg.generated
     */
    private Boolean privateOpenYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.write_subject_sn
     *
     * @mbg.generated
     */
    private Integer writeSubjectSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_sn
     *
     * @return the value of vote.vote_sn
     *
     * @mbg.generated
     */
    public Integer getVoteSn() {
        return voteSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_sn
     *
     * @param voteSn the value for vote.vote_sn
     *
     * @mbg.generated
     */
    public void setVoteSn(Integer voteSn) {
        this.voteSn = voteSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.category_sn
     *
     * @return the value of vote.category_sn
     *
     * @mbg.generated
     */
    public Integer getCategorySn() {
        return categorySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.category_sn
     *
     * @param categorySn the value for vote.category_sn
     *
     * @mbg.generated
     */
    public void setCategorySn(Integer categorySn) {
        this.categorySn = categorySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.start_date
     *
     * @return the value of vote.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.start_date
     *
     * @param startDate the value for vote.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.end_date
     *
     * @return the value of vote.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.end_date
     *
     * @param endDate the value for vote.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_name
     *
     * @return the value of vote.vote_name
     *
     * @mbg.generated
     */
    public String getVoteName() {
        return voteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_name
     *
     * @param voteName the value for vote.vote_name
     *
     * @mbg.generated
     */
    public void setVoteName(String voteName) {
        this.voteName = voteName == null ? null : voteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.content
     *
     * @return the value of vote.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.content
     *
     * @param content the value for vote.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.finish_yn
     *
     * @return the value of vote.finish_yn
     *
     * @mbg.generated
     */
    public Boolean getFinishYn() {
        return finishYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.finish_yn
     *
     * @param finishYn the value for vote.finish_yn
     *
     * @mbg.generated
     */
    public void setFinishYn(Boolean finishYn) {
        this.finishYn = finishYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.target_config_yn
     *
     * @return the value of vote.target_config_yn
     *
     * @mbg.generated
     */
    public Boolean getTargetConfigYn() {
        return targetConfigYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.target_config_yn
     *
     * @param targetConfigYn the value for vote.target_config_yn
     *
     * @mbg.generated
     */
    public void setTargetConfigYn(Boolean targetConfigYn) {
        this.targetConfigYn = targetConfigYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.target_vote_count
     *
     * @return the value of vote.target_vote_count
     *
     * @mbg.generated
     */
    public Integer getTargetVoteCount() {
        return targetVoteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.target_vote_count
     *
     * @param targetVoteCount the value for vote.target_vote_count
     *
     * @mbg.generated
     */
    public void setTargetVoteCount(Integer targetVoteCount) {
        this.targetVoteCount = targetVoteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.age_open_yn
     *
     * @return the value of vote.age_open_yn
     *
     * @mbg.generated
     */
    public Boolean getAgeOpenYn() {
        return ageOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.age_open_yn
     *
     * @param ageOpenYn the value for vote.age_open_yn
     *
     * @mbg.generated
     */
    public void setAgeOpenYn(Boolean ageOpenYn) {
        this.ageOpenYn = ageOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.sex_open_yn
     *
     * @return the value of vote.sex_open_yn
     *
     * @mbg.generated
     */
    public Boolean getSexOpenYn() {
        return sexOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.sex_open_yn
     *
     * @param sexOpenYn the value for vote.sex_open_yn
     *
     * @mbg.generated
     */
    public void setSexOpenYn(Boolean sexOpenYn) {
        this.sexOpenYn = sexOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.private_open_yn
     *
     * @return the value of vote.private_open_yn
     *
     * @mbg.generated
     */
    public Boolean getPrivateOpenYn() {
        return privateOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.private_open_yn
     *
     * @param privateOpenYn the value for vote.private_open_yn
     *
     * @mbg.generated
     */
    public void setPrivateOpenYn(Boolean privateOpenYn) {
        this.privateOpenYn = privateOpenYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.write_subject_sn
     *
     * @return the value of vote.write_subject_sn
     *
     * @mbg.generated
     */
    public Integer getWriteSubjectSn() {
        return writeSubjectSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.write_subject_sn
     *
     * @param writeSubjectSn the value for vote.write_subject_sn
     *
     * @mbg.generated
     */
    public void setWriteSubjectSn(Integer writeSubjectSn) {
        this.writeSubjectSn = writeSubjectSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Vote other = (Vote) that;
        return (this.getVoteSn() == null ? other.getVoteSn() == null : this.getVoteSn().equals(other.getVoteSn()))
            && (this.getCategorySn() == null ? other.getCategorySn() == null : this.getCategorySn().equals(other.getCategorySn()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getVoteName() == null ? other.getVoteName() == null : this.getVoteName().equals(other.getVoteName()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getFinishYn() == null ? other.getFinishYn() == null : this.getFinishYn().equals(other.getFinishYn()))
            && (this.getTargetConfigYn() == null ? other.getTargetConfigYn() == null : this.getTargetConfigYn().equals(other.getTargetConfigYn()))
            && (this.getTargetVoteCount() == null ? other.getTargetVoteCount() == null : this.getTargetVoteCount().equals(other.getTargetVoteCount()))
            && (this.getAgeOpenYn() == null ? other.getAgeOpenYn() == null : this.getAgeOpenYn().equals(other.getAgeOpenYn()))
            && (this.getSexOpenYn() == null ? other.getSexOpenYn() == null : this.getSexOpenYn().equals(other.getSexOpenYn()))
            && (this.getPrivateOpenYn() == null ? other.getPrivateOpenYn() == null : this.getPrivateOpenYn().equals(other.getPrivateOpenYn()))
            && (this.getWriteSubjectSn() == null ? other.getWriteSubjectSn() == null : this.getWriteSubjectSn().equals(other.getWriteSubjectSn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVoteSn() == null) ? 0 : getVoteSn().hashCode());
        result = prime * result + ((getCategorySn() == null) ? 0 : getCategorySn().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getVoteName() == null) ? 0 : getVoteName().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getFinishYn() == null) ? 0 : getFinishYn().hashCode());
        result = prime * result + ((getTargetConfigYn() == null) ? 0 : getTargetConfigYn().hashCode());
        result = prime * result + ((getTargetVoteCount() == null) ? 0 : getTargetVoteCount().hashCode());
        result = prime * result + ((getAgeOpenYn() == null) ? 0 : getAgeOpenYn().hashCode());
        result = prime * result + ((getSexOpenYn() == null) ? 0 : getSexOpenYn().hashCode());
        result = prime * result + ((getPrivateOpenYn() == null) ? 0 : getPrivateOpenYn().hashCode());
        result = prime * result + ((getWriteSubjectSn() == null) ? 0 : getWriteSubjectSn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", voteSn=").append(voteSn);
        sb.append(", categorySn=").append(categorySn);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", voteName=").append(voteName);
        sb.append(", content=").append(content);
        sb.append(", finishYn=").append(finishYn);
        sb.append(", targetConfigYn=").append(targetConfigYn);
        sb.append(", targetVoteCount=").append(targetVoteCount);
        sb.append(", ageOpenYn=").append(ageOpenYn);
        sb.append(", sexOpenYn=").append(sexOpenYn);
        sb.append(", privateOpenYn=").append(privateOpenYn);
        sb.append(", writeSubjectSn=").append(writeSubjectSn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}