package com.broduck.enigma.generate.model;

import java.io.Serializable;

public class VoteKind implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekind.vote_kind_sn
     *
     * @mbg.generated
     */
    private Integer voteKindSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekind.vote_kind_name
     *
     * @mbg.generated
     */
    private String voteKindName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votekind
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekind.vote_kind_sn
     *
     * @return the value of votekind.vote_kind_sn
     *
     * @mbg.generated
     */
    public Integer getVoteKindSn() {
        return voteKindSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekind.vote_kind_sn
     *
     * @param voteKindSn the value for votekind.vote_kind_sn
     *
     * @mbg.generated
     */
    public void setVoteKindSn(Integer voteKindSn) {
        this.voteKindSn = voteKindSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekind.vote_kind_name
     *
     * @return the value of votekind.vote_kind_name
     *
     * @mbg.generated
     */
    public String getVoteKindName() {
        return voteKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekind.vote_kind_name
     *
     * @param voteKindName the value for votekind.vote_kind_name
     *
     * @mbg.generated
     */
    public void setVoteKindName(String voteKindName) {
        this.voteKindName = voteKindName == null ? null : voteKindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekind
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoteKind other = (VoteKind) that;
        return (this.getVoteKindSn() == null ? other.getVoteKindSn() == null : this.getVoteKindSn().equals(other.getVoteKindSn()))
            && (this.getVoteKindName() == null ? other.getVoteKindName() == null : this.getVoteKindName().equals(other.getVoteKindName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekind
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVoteKindSn() == null) ? 0 : getVoteKindSn().hashCode());
        result = prime * result + ((getVoteKindName() == null) ? 0 : getVoteKindName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekind
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", voteKindSn=").append(voteKindSn);
        sb.append(", voteKindName=").append(voteKindName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}