package com.broduck.enigma.generate.model;

import java.io.Serializable;

public class VoteKindDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekinddetail.vote_kind_detail_sn
     *
     * @mbg.generated
     */
    private Integer voteKindDetailSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekinddetail.vote_kind_sn
     *
     * @mbg.generated
     */
    private Integer voteKindSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekinddetail.default_photo
     *
     * @mbg.generated
     */
    private String defaultPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votekinddetail.default_vote_item_name
     *
     * @mbg.generated
     */
    private String defaultVoteItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votekinddetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekinddetail.vote_kind_detail_sn
     *
     * @return the value of votekinddetail.vote_kind_detail_sn
     *
     * @mbg.generated
     */
    public Integer getVoteKindDetailSn() {
        return voteKindDetailSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekinddetail.vote_kind_detail_sn
     *
     * @param voteKindDetailSn the value for votekinddetail.vote_kind_detail_sn
     *
     * @mbg.generated
     */
    public void setVoteKindDetailSn(Integer voteKindDetailSn) {
        this.voteKindDetailSn = voteKindDetailSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekinddetail.vote_kind_sn
     *
     * @return the value of votekinddetail.vote_kind_sn
     *
     * @mbg.generated
     */
    public Integer getVoteKindSn() {
        return voteKindSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekinddetail.vote_kind_sn
     *
     * @param voteKindSn the value for votekinddetail.vote_kind_sn
     *
     * @mbg.generated
     */
    public void setVoteKindSn(Integer voteKindSn) {
        this.voteKindSn = voteKindSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekinddetail.default_photo
     *
     * @return the value of votekinddetail.default_photo
     *
     * @mbg.generated
     */
    public String getDefaultPhoto() {
        return defaultPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekinddetail.default_photo
     *
     * @param defaultPhoto the value for votekinddetail.default_photo
     *
     * @mbg.generated
     */
    public void setDefaultPhoto(String defaultPhoto) {
        this.defaultPhoto = defaultPhoto == null ? null : defaultPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votekinddetail.default_vote_item_name
     *
     * @return the value of votekinddetail.default_vote_item_name
     *
     * @mbg.generated
     */
    public String getDefaultVoteItemName() {
        return defaultVoteItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votekinddetail.default_vote_item_name
     *
     * @param defaultVoteItemName the value for votekinddetail.default_vote_item_name
     *
     * @mbg.generated
     */
    public void setDefaultVoteItemName(String defaultVoteItemName) {
        this.defaultVoteItemName = defaultVoteItemName == null ? null : defaultVoteItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekinddetail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoteKindDetail other = (VoteKindDetail) that;
        return (this.getVoteKindDetailSn() == null ? other.getVoteKindDetailSn() == null : this.getVoteKindDetailSn().equals(other.getVoteKindDetailSn()))
            && (this.getVoteKindSn() == null ? other.getVoteKindSn() == null : this.getVoteKindSn().equals(other.getVoteKindSn()))
            && (this.getDefaultPhoto() == null ? other.getDefaultPhoto() == null : this.getDefaultPhoto().equals(other.getDefaultPhoto()))
            && (this.getDefaultVoteItemName() == null ? other.getDefaultVoteItemName() == null : this.getDefaultVoteItemName().equals(other.getDefaultVoteItemName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekinddetail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVoteKindDetailSn() == null) ? 0 : getVoteKindDetailSn().hashCode());
        result = prime * result + ((getVoteKindSn() == null) ? 0 : getVoteKindSn().hashCode());
        result = prime * result + ((getDefaultPhoto() == null) ? 0 : getDefaultPhoto().hashCode());
        result = prime * result + ((getDefaultVoteItemName() == null) ? 0 : getDefaultVoteItemName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votekinddetail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", voteKindDetailSn=").append(voteKindDetailSn);
        sb.append(", voteKindSn=").append(voteKindSn);
        sb.append(", defaultPhoto=").append(defaultPhoto);
        sb.append(", defaultVoteItemName=").append(defaultVoteItemName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}