package com.broduck.enigma.generate.model;

import java.io.Serializable;

public class VoteJoinMember implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votejoinmember.vote_join_sn
     *
     * @mbg.generated
     */
    private Integer voteJoinSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votejoinmember.member_sn
     *
     * @mbg.generated
     */
    private Integer memberSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votejoinmember.vote_sn
     *
     * @mbg.generated
     */
    private Integer voteSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votejoinmember.vote_join_sn
     *
     * @return the value of votejoinmember.vote_join_sn
     *
     * @mbg.generated
     */
    public Integer getVoteJoinSn() {
        return voteJoinSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votejoinmember.vote_join_sn
     *
     * @param voteJoinSn the value for votejoinmember.vote_join_sn
     *
     * @mbg.generated
     */
    public void setVoteJoinSn(Integer voteJoinSn) {
        this.voteJoinSn = voteJoinSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votejoinmember.member_sn
     *
     * @return the value of votejoinmember.member_sn
     *
     * @mbg.generated
     */
    public Integer getMemberSn() {
        return memberSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votejoinmember.member_sn
     *
     * @param memberSn the value for votejoinmember.member_sn
     *
     * @mbg.generated
     */
    public void setMemberSn(Integer memberSn) {
        this.memberSn = memberSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votejoinmember.vote_sn
     *
     * @return the value of votejoinmember.vote_sn
     *
     * @mbg.generated
     */
    public Integer getVoteSn() {
        return voteSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votejoinmember.vote_sn
     *
     * @param voteSn the value for votejoinmember.vote_sn
     *
     * @mbg.generated
     */
    public void setVoteSn(Integer voteSn) {
        this.voteSn = voteSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoteJoinMember other = (VoteJoinMember) that;
        return (this.getVoteJoinSn() == null ? other.getVoteJoinSn() == null : this.getVoteJoinSn().equals(other.getVoteJoinSn()))
            && (this.getMemberSn() == null ? other.getMemberSn() == null : this.getMemberSn().equals(other.getMemberSn()))
            && (this.getVoteSn() == null ? other.getVoteSn() == null : this.getVoteSn().equals(other.getVoteSn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getVoteJoinSn() == null) ? 0 : getVoteJoinSn().hashCode());
        result = prime * result + ((getMemberSn() == null) ? 0 : getMemberSn().hashCode());
        result = prime * result + ((getVoteSn() == null) ? 0 : getVoteSn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votejoinmember
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", voteJoinSn=").append(voteJoinSn);
        sb.append(", memberSn=").append(memberSn);
        sb.append(", voteSn=").append(voteSn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}