package com.broduck.enigma.generate.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vote
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public VoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoteSnIsNull() {
            addCriterion("vote_sn is null");
            return (Criteria) this;
        }

        public Criteria andVoteSnIsNotNull() {
            addCriterion("vote_sn is not null");
            return (Criteria) this;
        }

        public Criteria andVoteSnEqualTo(Integer value) {
            addCriterion("vote_sn =", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotEqualTo(Integer value) {
            addCriterion("vote_sn <>", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnGreaterThan(Integer value) {
            addCriterion("vote_sn >", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_sn >=", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnLessThan(Integer value) {
            addCriterion("vote_sn <", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnLessThanOrEqualTo(Integer value) {
            addCriterion("vote_sn <=", value, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnIn(List<Integer> values) {
            addCriterion("vote_sn in", values, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotIn(List<Integer> values) {
            addCriterion("vote_sn not in", values, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnBetween(Integer value1, Integer value2) {
            addCriterion("vote_sn between", value1, value2, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteSnNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_sn not between", value1, value2, "voteSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnIsNull() {
            addCriterion("vote_kind_sn is null");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnIsNotNull() {
            addCriterion("vote_kind_sn is not null");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnEqualTo(Integer value) {
            addCriterion("vote_kind_sn =", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnNotEqualTo(Integer value) {
            addCriterion("vote_kind_sn <>", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnGreaterThan(Integer value) {
            addCriterion("vote_kind_sn >", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_kind_sn >=", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnLessThan(Integer value) {
            addCriterion("vote_kind_sn <", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnLessThanOrEqualTo(Integer value) {
            addCriterion("vote_kind_sn <=", value, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnIn(List<Integer> values) {
            addCriterion("vote_kind_sn in", values, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnNotIn(List<Integer> values) {
            addCriterion("vote_kind_sn not in", values, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnBetween(Integer value1, Integer value2) {
            addCriterion("vote_kind_sn between", value1, value2, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andVoteKindSnNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_kind_sn not between", value1, value2, "voteKindSn");
            return (Criteria) this;
        }

        public Criteria andCategorySnIsNull() {
            addCriterion("category_sn is null");
            return (Criteria) this;
        }

        public Criteria andCategorySnIsNotNull() {
            addCriterion("category_sn is not null");
            return (Criteria) this;
        }

        public Criteria andCategorySnEqualTo(Integer value) {
            addCriterion("category_sn =", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnNotEqualTo(Integer value) {
            addCriterion("category_sn <>", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnGreaterThan(Integer value) {
            addCriterion("category_sn >", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_sn >=", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnLessThan(Integer value) {
            addCriterion("category_sn <", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnLessThanOrEqualTo(Integer value) {
            addCriterion("category_sn <=", value, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnIn(List<Integer> values) {
            addCriterion("category_sn in", values, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnNotIn(List<Integer> values) {
            addCriterion("category_sn not in", values, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnBetween(Integer value1, Integer value2) {
            addCriterion("category_sn between", value1, value2, "categorySn");
            return (Criteria) this;
        }

        public Criteria andCategorySnNotBetween(Integer value1, Integer value2) {
            addCriterion("category_sn not between", value1, value2, "categorySn");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andVoteNameIsNull() {
            addCriterion("vote_name is null");
            return (Criteria) this;
        }

        public Criteria andVoteNameIsNotNull() {
            addCriterion("vote_name is not null");
            return (Criteria) this;
        }

        public Criteria andVoteNameEqualTo(String value) {
            addCriterion("vote_name =", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotEqualTo(String value) {
            addCriterion("vote_name <>", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameGreaterThan(String value) {
            addCriterion("vote_name >", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameGreaterThanOrEqualTo(String value) {
            addCriterion("vote_name >=", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLessThan(String value) {
            addCriterion("vote_name <", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLessThanOrEqualTo(String value) {
            addCriterion("vote_name <=", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameLike(String value) {
            addCriterion("vote_name like", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotLike(String value) {
            addCriterion("vote_name not like", value, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameIn(List<String> values) {
            addCriterion("vote_name in", values, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotIn(List<String> values) {
            addCriterion("vote_name not in", values, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameBetween(String value1, String value2) {
            addCriterion("vote_name between", value1, value2, "voteName");
            return (Criteria) this;
        }

        public Criteria andVoteNameNotBetween(String value1, String value2) {
            addCriterion("vote_name not between", value1, value2, "voteName");
            return (Criteria) this;
        }

        public Criteria andFinishYnIsNull() {
            addCriterion("finish_yn is null");
            return (Criteria) this;
        }

        public Criteria andFinishYnIsNotNull() {
            addCriterion("finish_yn is not null");
            return (Criteria) this;
        }

        public Criteria andFinishYnEqualTo(Boolean value) {
            addCriterion("finish_yn =", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnNotEqualTo(Boolean value) {
            addCriterion("finish_yn <>", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnGreaterThan(Boolean value) {
            addCriterion("finish_yn >", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnGreaterThanOrEqualTo(Boolean value) {
            addCriterion("finish_yn >=", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnLessThan(Boolean value) {
            addCriterion("finish_yn <", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnLessThanOrEqualTo(Boolean value) {
            addCriterion("finish_yn <=", value, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnIn(List<Boolean> values) {
            addCriterion("finish_yn in", values, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnNotIn(List<Boolean> values) {
            addCriterion("finish_yn not in", values, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnBetween(Boolean value1, Boolean value2) {
            addCriterion("finish_yn between", value1, value2, "finishYn");
            return (Criteria) this;
        }

        public Criteria andFinishYnNotBetween(Boolean value1, Boolean value2) {
            addCriterion("finish_yn not between", value1, value2, "finishYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnIsNull() {
            addCriterion("target_config_yn is null");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnIsNotNull() {
            addCriterion("target_config_yn is not null");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnEqualTo(Boolean value) {
            addCriterion("target_config_yn =", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnNotEqualTo(Boolean value) {
            addCriterion("target_config_yn <>", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnGreaterThan(Boolean value) {
            addCriterion("target_config_yn >", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnGreaterThanOrEqualTo(Boolean value) {
            addCriterion("target_config_yn >=", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnLessThan(Boolean value) {
            addCriterion("target_config_yn <", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnLessThanOrEqualTo(Boolean value) {
            addCriterion("target_config_yn <=", value, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnIn(List<Boolean> values) {
            addCriterion("target_config_yn in", values, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnNotIn(List<Boolean> values) {
            addCriterion("target_config_yn not in", values, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnBetween(Boolean value1, Boolean value2) {
            addCriterion("target_config_yn between", value1, value2, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetConfigYnNotBetween(Boolean value1, Boolean value2) {
            addCriterion("target_config_yn not between", value1, value2, "targetConfigYn");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountIsNull() {
            addCriterion("target_vote_count is null");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountIsNotNull() {
            addCriterion("target_vote_count is not null");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountEqualTo(Integer value) {
            addCriterion("target_vote_count =", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountNotEqualTo(Integer value) {
            addCriterion("target_vote_count <>", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountGreaterThan(Integer value) {
            addCriterion("target_vote_count >", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("target_vote_count >=", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountLessThan(Integer value) {
            addCriterion("target_vote_count <", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountLessThanOrEqualTo(Integer value) {
            addCriterion("target_vote_count <=", value, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountIn(List<Integer> values) {
            addCriterion("target_vote_count in", values, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountNotIn(List<Integer> values) {
            addCriterion("target_vote_count not in", values, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountBetween(Integer value1, Integer value2) {
            addCriterion("target_vote_count between", value1, value2, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andTargetVoteCountNotBetween(Integer value1, Integer value2) {
            addCriterion("target_vote_count not between", value1, value2, "targetVoteCount");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeIsNull() {
            addCriterion("open_scope_code is null");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeIsNotNull() {
            addCriterion("open_scope_code is not null");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeEqualTo(String value) {
            addCriterion("open_scope_code =", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeNotEqualTo(String value) {
            addCriterion("open_scope_code <>", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeGreaterThan(String value) {
            addCriterion("open_scope_code >", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("open_scope_code >=", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeLessThan(String value) {
            addCriterion("open_scope_code <", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeLessThanOrEqualTo(String value) {
            addCriterion("open_scope_code <=", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeLike(String value) {
            addCriterion("open_scope_code like", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeNotLike(String value) {
            addCriterion("open_scope_code not like", value, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeIn(List<String> values) {
            addCriterion("open_scope_code in", values, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeNotIn(List<String> values) {
            addCriterion("open_scope_code not in", values, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeBetween(String value1, String value2) {
            addCriterion("open_scope_code between", value1, value2, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeNotBetween(String value1, String value2) {
            addCriterion("open_scope_code not between", value1, value2, "openScopeCode");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnIsNull() {
            addCriterion("wtire_subject_sn is null");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnIsNotNull() {
            addCriterion("wtire_subject_sn is not null");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnEqualTo(Integer value) {
            addCriterion("wtire_subject_sn =", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnNotEqualTo(Integer value) {
            addCriterion("wtire_subject_sn <>", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnGreaterThan(Integer value) {
            addCriterion("wtire_subject_sn >", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("wtire_subject_sn >=", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnLessThan(Integer value) {
            addCriterion("wtire_subject_sn <", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnLessThanOrEqualTo(Integer value) {
            addCriterion("wtire_subject_sn <=", value, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnIn(List<Integer> values) {
            addCriterion("wtire_subject_sn in", values, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnNotIn(List<Integer> values) {
            addCriterion("wtire_subject_sn not in", values, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnBetween(Integer value1, Integer value2) {
            addCriterion("wtire_subject_sn between", value1, value2, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andWtireSubjectSnNotBetween(Integer value1, Integer value2) {
            addCriterion("wtire_subject_sn not between", value1, value2, "wtireSubjectSn");
            return (Criteria) this;
        }

        public Criteria andVoteNameLikeInsensitive(String value) {
            addCriterion("upper(vote_name) like", value.toUpperCase(), "voteName");
            return (Criteria) this;
        }

        public Criteria andOpenScopeCodeLikeInsensitive(String value) {
            addCriterion("upper(open_scope_code) like", value.toUpperCase(), "openScopeCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vote
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}